source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

workspace 'DummyProject/Dummy.xcworkspace'

target 'DummyFramework' do
  project 'DummyProject/Dummy.xcodeproj'

  pod 'Alamofire',                '>= 4.7.3'
  pod 'Armchair',                 '>= 0.3.5'
# pod 'Bolts',                    '>= 1.9.0'
  pod 'CryptoSwift',              '>= 0.12.0'
# pod 'Differentiator',           '>= 3.0.2'
  pod 'Dispatch',                 '>= 2.0.4'
  pod 'FBSDKCoreKit',             '>= 4.37.0' # Bolts
  pod 'GoogleAnalytics',          '>= 3.17.0'
  pod 'GzipSwift',                '>= 4.0.4'
  pod 'HMSegmentedControl',       '>= 1.5.3'
  pod 'INTULocationManager',      '>= 4.3.0'
  pod 'KeychainAccess',           '>= 3.1.0'
  pod 'MBProgressHUD',            '>= 1.1.0'
  pod 'MXPagerView',              '>= 0.2.1'
  pod 'MXParallaxHeader',         '>= 0.6.1'
  pod 'MXSegmentedPager',         '>= 3.3.0'
  pod 'PDTSimpleCalendar',        '>= 0.9.1'
  pod 'PureLayout',               '>= 3.1.2'
  pod 'R.swift',                  '>= 4.0.0'  # R.swift.Library
# pod 'R.swift.Library',          '>= 4.0.0'
  pod 'ROStorageBar',             '>= 2.1.3'
# pod 'RxCocoa',                  '>= 4.1.2'  # RxSwift
  pod 'RxDataSources',            '>= 3.0.2'  # Differentiator, RxCocoa
# pod 'RxSwift',                  '>= 4.1.2'
  pod 'SDWebImage/Core',          '>= 4.4.2'
  pod 'Siren',                    '>= 3.2.3'
  pod 'SlideMenuControllerSwift', '>= 4.0.0'
  pod 'SQLCipher/standard',       '>= 3.4.2'
  pod 'SQLite.swift/SQLCipher',   '>= 0.11.4'
  pod 'SwiftReorder',             '>= 6.0.0'
  pod 'SwiftyJSON',               '>= 4.2.0'
  pod 'Toast',                    '>= 4.0.0'
  pod 'YandexMobileMetrica',      '>= 2.9.8', '< 3.0.0'
end
